<script setup lang="ts">
// ============================================================================
// PostsIndex.vue — the post index landing, with pagination (POST-001)
// ============================================================================
// Rendered by both `src/posts.md` (page 1) and `src/page/[num].md` (pages ≥ 2).
// It reads the build-time post list, slices the current page, and renders the
// rich post cards (PostList) plus prev/next/number pagination. Page 1 lives at
// `/posts`; deeper pages at `/page/<n>` — matching the paths generated by
// `src/page/[num].paths.mjs`. This is the "more visually rich landing page" the
// content architecture distinguishes from the plain archives timeline
// (content-architecture.md §3).
import { computed } from 'vue'
import { useData, withBase } from 'vitepress'
import { data as posts } from '../posts.data.mts'
import { POSTS_PER_PAGE, filterListablePosts, pageCount } from '../posts'
import { useThemeConfig } from '../composables/useThemeConfig'
import { useThemeLocale } from '../composables/useThemeLocale'
import PostList from './PostList.vue'

const { params } = useData()
const { t } = useThemeLocale()
const config = useThemeConfig()

// Series articles join only when opted in (POST-002). The page/[num] route
// loader applies the same filter, so page count and routes agree.
const listable = computed(() =>
  filterListablePosts(posts, config.value.series, 'posts'),
)

// Current page: `/page/[num]` supplies `num`; `/posts` has no params (page 1).
const current = computed(() => {
  const raw = (params.value as { num?: string | number } | null)?.num
  const parsed = typeof raw === 'string' ? parseInt(raw, 10) : Number(raw)
  return Number.isFinite(parsed) && parsed >= 1 ? parsed : 1
})

const totalPages = computed(() => pageCount(listable.value.length))

const pagePosts = computed(() => {
  const start = (current.value - 1) * POSTS_PER_PAGE
  return listable.value.slice(start, start + POSTS_PER_PAGE)
})

// Page 1 is the `/posts` index; every later page is `/page/<n>`.
function pageHref(n: number): string {
  return withBase(n <= 1 ? '/posts' : `/page/${n}`)
}

const pageNumbers = computed(() =>
  Array.from({ length: totalPages.value }, (_, i) => i + 1),
)
</script>

<template>
  <div class="ct-listing ct-posts-index">
    <h1 class="ct-listing__title">{{ t('post.postsTitle') }}</h1>

    <PostList :posts="pagePosts" />

    <!-- Pagination: prev · numbered pages · next (only with more than one) -->
    <nav
      v-if="totalPages > 1"
      class="ct-pagination"
      :aria-label="t('post.pagination')"
    >
      <a
        v-if="current > 1"
        class="ct-pagination__link ct-pagination__prev"
        :href="pageHref(current - 1)"
        >{{ t('post.prevPage') }}</a
      >
      <a
        v-for="n in pageNumbers"
        :key="n"
        class="ct-pagination__link ct-pagination__num"
        :class="{ 'ct-pagination__num--active': n === current }"
        :href="pageHref(n)"
        :aria-current="n === current ? 'page' : undefined"
        >{{ n }}</a
      >
      <a
        v-if="current < totalPages"
        class="ct-pagination__link ct-pagination__next"
        :href="pageHref(current + 1)"
        >{{ t('post.nextPage') }}</a
      >
    </nav>
  </div>
</template>
