<script setup lang="ts">
// ============================================================================
// PostTaxonomy.vue — a post's categories & tags as links (POST-001)
// ============================================================================
// Shared by the post header (PostPage.vue) and post cards (PostList.vue): the
// "post metadata links to them" requirement. Categories link to
// `/categories/<slug>`, tags to `/tags/<slug>`; the slug matches the dynamic
// routes generated by `src/{categories,tags}/[name].paths.mjs`. Group labels
// are localized; term display names resolve through `themeConfig.taxonomy`
// (I18N-008) and fall back to the authored name — slugs/URLs stay authored.
import { withBase } from 'vitepress'
import { slugify } from '../posts'
import { useTaxonomy } from '../composables/useTaxonomy'
import { useThemeLocale } from '../composables/useThemeLocale'

defineProps<{
  categories?: string[]
  tags?: string[]
}>()

const { t } = useThemeLocale()
const { tagLabel, categoryLabel } = useTaxonomy()

function categoryHref(name: string): string {
  return withBase(`/categories/${slugify(name)}`)
}
function tagHref(name: string): string {
  return withBase(`/tags/${slugify(name)}`)
}
</script>

<template>
  <div class="ct-taxonomy">
    <!-- Categories: the broad grouping, prefixed with a folder-style marker -->
    <span
      v-if="categories && categories.length"
      class="ct-taxonomy__group ct-taxonomy__group--categories"
    >
      <span class="ct-taxonomy__label">{{ t('post.categories') }}</span>
      <a
        v-for="name in categories"
        :key="name"
        class="ct-taxonomy__term ct-taxonomy__term--category"
        :href="categoryHref(name)"
        >{{ categoryLabel(name) }}</a
      >
    </span>

    <!-- Tags: the fine-grained keywords, prefixed with a `#` marker -->
    <span
      v-if="tags && tags.length"
      class="ct-taxonomy__group ct-taxonomy__group--tags"
    >
      <span class="ct-taxonomy__label">{{ t('post.tags') }}</span>
      <a
        v-for="name in tags"
        :key="name"
        class="ct-taxonomy__term ct-taxonomy__term--tag"
        :href="tagHref(name)"
        >#{{ tagLabel(name) }}</a
      >
    </span>
  </div>
</template>
